# Generated by Django 3.1.2 on 2020-11-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0021_auto_20201112_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='likes', to='crud.Profile'),
        ),
    ]
