# Generated by Django 3.1.2 on 2020-11-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0023_auto_20201113_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], max_length=8),
        ),
    ]
