# Generated by Django 3.1.2 on 2020-11-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0025_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ser',
            new_name='user',
        ),
    ]
